[package]
name = "loadTomlToElement"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
colored = "3.0.0"
# serde_toml = "0.0.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
toml = "0.8.23"
